### ISSUE TITLE
Add usage/installation instructions

### ISSUE THREAD

**Issue by Tafubitto** [blackspherefollower/buttplug4j#17]
I would love to contribute or use this, but I don't know how to get started. A tutorial link in the README on how to import and use it in Eclipse would be much appreciated.

**Comment by blackspherefollower** [comment]
Buttplug4J uses gradle in a pretty standard way (intellij will just open it as a java project). It seems eclipse still requires extra plugsins: https://www.tutorialspoint.com/gradle/gradle_eclipse_integration.htm

I'm not going to rule out contributions, but I think it'd be a good idea to open issues to discuss any changes before you spend time implementing them.

**Comment by Cind3r** [comment]
I'm just now coming across this project as I'm trying to integrate Intiface with a java-based game, however, I'm having the same issue as the commentator above. 

I'm not new to programming, but haven't worked a ton with java, and I'm finding it incredibly difficult to understand how to implement this in an already existing code base. Frankly, I can't even get it to work stand-alone in Intellij after installing all dependencies.

Could the README be update with examples of implementing this into actual scripts/use cases?

**Comment by blackspherefollower** [comment]
OK, so I've just created an example project repo: https://github.com/blackspherefollower/buttplug4j-example

You shouldn't be downloading dependencies manually, Gradle is way to go these days (Maven might still be lingering in places though).

**Comment by blackspherefollower** [comment]
Since I've not had any feedback either way, I'll close this now.
Please comment or raise new issues if there's areas of usage that need more clarity
